# Generated by Django 3.1.7 on 2021-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_lib', '0004_book_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
